# Actuator Web 访问端口
management.server.port=8081
# 通过JMX协议暴露所有的监控端点。
management.endpoints.jmx.exposure.include=*
# 通过HTTP协议暴露所有的监控端点。
management.endpoints.web.exposure.include=*
# 开启健康检查的完整信息
management.endpoint.health.show-details=always

# 应用服务 WEB 访问端口
server.port=8080

