# profile的配置方式
# 方式2 yml多文档方式
# 激活方式：
# 1. 配置文件，如本文档所示
# 2. 虚拟机参数 -Dspring.profiles.active=test
# 3. 命令行参数 java -jar springboot-03-profiles-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod

spring:
  profiles:
    active: dev
    # 默认激活dev环境

---
# 开发环境配置
server:
  port: 8082
spring:
  config:
    activate:
      on-profile: dev

---
# 测试环境配置
server:
  port: 8083
spring:
  config:
    activate:
      on-profile: test

---
# 生产环境配置
server:
  port: 8084
spring:
  config:
    activate:
      on-profile: prod